#ifndef BASE_H
#define BASE_H
#include <QString>
#include <vector>
#include <array>
#include <utility>
#include <QFile>
#include <QJsonDocument>
#include <QDebug>
#include <set>
#include <QDir>
#include <QJsonArray>
#include <QJsonObject>
#include <map>
#include <QTextStream>
#include <iostream>
#include <algorithm>
#include <random>
#include <ctime>
#include <chrono>
#include <QRegExp>
#include <functional>
#include <randlib.h>
#define _MY_DEBUG_
#endif // BASE_H
